-- Copyright (c) 2026 Likeon. Licensed under the MIT License.
--
-- business_example.lua — all business logic in Lua, including code handling.
-- Shows the pattern; adapt command codes / payloads to your needs.

local relay     = require("native_relay")
local Cmd       = require("relay_command")   -- generated by tools/codegen (single source of truth)
local RelayCode = CS.Likeon.NativeRelay.RelayCode

relay.init(5.0)

-- Example 1: device info (GetDeviceInfo = 7; data = json string)
relay.request(Cmd.GetDeviceInfo, nil, function(ok, code, data)
    if ok then
        print("device info json:", data)          -- decode with your json lib
    elseif code == RelayCode.Timeout then
        print("device info: timeout")
    else
        print("device info failed, code:", code, data)
    end
end)

-- Example 2: request the camera permission (payload = "camera")
relay.request(Cmd.RequestPermission, "camera", function(ok, code, data)
    if ok then
        print("camera permission granted")
    else
        print("camera permission denied/restricted, code:", code)
    end
end)

-- Example 3: one-shot location (GetLocationOnce = 2; data = json {lat,lng,acc})
relay.request(Cmd.GetLocationOnce, nil, function(ok, code, data)
    if ok then
        print("location json:", data)
    else
        print("location failed, code:", code)
    end
end)

-- On scene change / shutdown:
-- relay.dispose()
