// AUTO-GENERATED by tools/codegen/gen.py from commands.json — DO NOT EDIT BY HAND.

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, RelayCommand) {
    // Request a runtime permission (payload = camera/microphone/photos/location/notification)
    RelayCommandRequestPermission = 1,
    // One-shot location; data = json {lat,lng,acc}
    RelayCommandGetLocationOnce = 2,
    // Pick image/video from the library; data = file path
    RelayCommandPickMedia = 3,
    // Save a file to the photo album
    RelayCommandSaveToAlbum = 4,
    // Capture a photo with the system camera; data = file path
    RelayCommandCapturePhoto = 5,
    // Scan a QR/barcode; data = scanned string
    RelayCommandScanCode = 6,
    // Device/system info; data = json
    RelayCommandGetDeviceInfo = 7,
    // Network status; data = wifi/cellular/ethernet/none
    RelayCommandGetNetworkStatus = 8,
    // Vibrate/haptic (payload = light/medium/heavy or ms:<n>)
    RelayCommandVibrate = 9,
    // Open app/notification settings (payload = app/notification/store-review)
    RelayCommandOpenSettings = 10,
};
