#!/usr/bin/env python3
# Copyright (c) 2026 Likeon. Licensed under the MIT License.
"""
NativeRelay command-code generator.

One source of truth (commands.json) -> four ends (C# / Java / Lua / Objective-C),
so a multi-platform project never hand-aligns the same int command codes again.

Usage:
    python gen.py            # (re)generate into ./generated/
    python gen.py --check    # generate in memory, fail (exit 1) if ./generated/ is stale
                             # -> use this in CI to catch "edited json, forgot to regenerate"

Design rules this enforces / encourages (see README):
  - values are explicit (never auto-incremented)        -> validated here
  - no duplicate names, no duplicate values             -> validated here
  - generated files are marked AUTO-GENERATED           -> emitted in every header
"""
import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "commands.json"
OUT = HERE / "generated"


def to_upper_snake(name: str) -> str:
    """StartRecord -> START_RECORD ; HTTPProxy -> HTTP_PROXY (good enough for command names)."""
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
    return s.upper()


def load_spec() -> dict:
    # utf-8-sig tolerates a UTF-8 BOM, which Windows editors / PowerShell often add.
    spec = json.loads(SRC.read_text(encoding="utf-8-sig"))
    cmds = spec.get("commands", [])
    if not cmds:
        sys.exit("error: no commands in commands.json")

    seen_names, seen_values = {}, {}
    for c in cmds:
        name, value = c.get("name"), c.get("value")
        if not isinstance(name, str) or not name:
            sys.exit(f"error: command missing a string 'name': {c}")
        if not isinstance(value, int):
            sys.exit(f"error: command '{name}' missing an integer 'value'")
        if name in seen_names:
            sys.exit(f"error: duplicate command name '{name}'")
        if value in seen_values:
            sys.exit(f"error: value {value} reused by '{name}' and '{seen_values[value]}'")
        seen_names[name] = value
        seen_values[value] = name
    return spec


HEADER = "// AUTO-GENERATED by tools/codegen/gen.py from commands.json — DO NOT EDIT BY HAND."
LUA_HEADER = "-- AUTO-GENERATED by tools/codegen/gen.py from commands.json — DO NOT EDIT BY HAND."


def gen_csharp(spec: dict) -> str:
    enum, ns = spec["enumName"], spec["csharpNamespace"]
    lines = [HEADER, "", f"namespace {ns}", "{", f"    public enum {enum}", "    {"]
    for c in spec["commands"]:
        if c.get("desc"):
            lines.append(f"        /// <summary>{c['desc']}</summary>")
        lines.append(f"        {c['name']} = {c['value']},")
    lines += ["    }", "}", ""]
    return "\n".join(lines)


def gen_java(spec: dict) -> str:
    enum, pkg = spec["enumName"], spec["javaPackage"]
    lines = [HEADER, "", f"package {pkg};", "",
             f"/** Command codes for NativeRelay. Switch on these int values in your channel. */",
             f"public final class {enum} {{",
             f"    private {enum}() {{}}", ""]
    for c in spec["commands"]:
        if c.get("desc"):
            lines.append(f"    /** {c['desc']} */")
        lines.append(f"    public static final int {to_upper_snake(c['name'])} = {c['value']};")
    lines += ["}", ""]
    return "\n".join(lines)


def gen_lua(spec: dict) -> str:
    enum = spec["enumName"]
    lines = [LUA_HEADER, "", f"local {enum} = {{"]
    for c in spec["commands"]:
        comment = f"  -- {c['desc']}" if c.get("desc") else ""
        lines.append(f"    {c['name']} = {c['value']},{comment}")
    lines += ["}", "", f"return {enum}", ""]
    return "\n".join(lines)


def gen_objc(spec: dict) -> str:
    enum = spec["enumName"]
    lines = [HEADER, "", "#import <Foundation/Foundation.h>", "",
             f"typedef NS_ENUM(NSInteger, {enum}) {{"]
    for c in spec["commands"]:
        if c.get("desc"):
            lines.append(f"    // {c['desc']}")
        lines.append(f"    {enum}{c['name']} = {c['value']},")
    lines += ["};", ""]
    return "\n".join(lines)


# Each target emits straight into the place that actually compiles it, so there's no second
# copy to keep in sync. Java -> the Android module; Obj-C -> ios/Source; C#/Lua have no host
# project in this repo, so they land in generated/ as a reference to copy into your Unity app.
REPO = HERE.parent.parent
ANDROID_PKG = REPO / "android" / "nativerelay" / "src" / "main" / "java" / "com" / "likeon" / "nativerelay"
IOS_SRC = REPO / "ios" / "Source"

TARGETS = {
    "RelayCommand.cs": (gen_csharp, OUT),
    "relay_command.lua": (gen_lua, OUT),
    "RelayCommand.java": (gen_java, ANDROID_PKG),
    "RelayCommand.h": (gen_objc, IOS_SRC),
}


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate NativeRelay command codes for 4 platforms.")
    ap.add_argument("--check", action="store_true",
                    help="don't write; exit 1 if generated/ is missing or stale (for CI).")
    args = ap.parse_args()

    spec = load_spec()
    wanted = {name: (fn(spec), outdir) for name, (fn, outdir) in TARGETS.items()}

    if args.check:
        stale = []
        for name, (content, outdir) in wanted.items():
            path = outdir / name
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(name)
        if stale:
            print("STALE (run `python gen.py`): " + ", ".join(stale), file=sys.stderr)
            return 1
        print("OK: generated files are up to date.")
        return 0

    for name, (content, outdir) in wanted.items():
        outdir.mkdir(parents=True, exist_ok=True)
        (outdir / name).write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {(outdir / name).relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
