// AUTO-GENERATED by tools/codegen/gen.py from commands.json — DO NOT EDIT BY HAND.

package com.likeon.nativerelay;

/** Command codes for NativeRelay. Switch on these int values in your channel. */
public final class RelayCommand {
    private RelayCommand() {}

    /** Request a runtime permission (payload = camera/microphone/photos/location/notification) */
    public static final int REQUEST_PERMISSION = 1;
    /** One-shot location; data = json {lat,lng,acc} */
    public static final int GET_LOCATION_ONCE = 2;
    /** Pick image/video from the library; data = file path */
    public static final int PICK_MEDIA = 3;
    /** Save a file to the photo album */
    public static final int SAVE_TO_ALBUM = 4;
    /** Capture a photo with the system camera; data = file path */
    public static final int CAPTURE_PHOTO = 5;
    /** Scan a QR/barcode; data = scanned string */
    public static final int SCAN_CODE = 6;
    /** Device/system info; data = json */
    public static final int GET_DEVICE_INFO = 7;
    /** Network status; data = wifi/cellular/ethernet/none */
    public static final int GET_NETWORK_STATUS = 8;
    /** Vibrate/haptic (payload = light/medium/heavy or ms:<n>) */
    public static final int VIBRATE = 9;
    /** Open app/notification settings (payload = app/notification/store-review) */
    public static final int OPEN_SETTINGS = 10;
}
